-- Bingescape Initial Data
-- Insert sample web series records for vickyram.vira@gmail.com

INSERT INTO bingescape (
  user_id,
  title,
  verse,
  description,
  season,
  genres,
  language,
  start_date,
  end_date,
  star_rating,
  watch_download_link,
  poster_image_url,
  comment
) VALUES 
-- Crime Series
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Bones',
  'Crime',
  'Anthropologist helps FBI solve cases',
  '1',
  ARRAY['Crime', 'Drama', 'Mystery'],
  'English',
  '05/09',
  '03/17',
  3,
  'Hotstar',
  NULL,
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Brooklyn Nine-Nine',
  'Crime',
  'Comical police story',
  '1',
  ARRAY['Comedy', 'Crime'],
  'English',
  '09/13',
  '09/21',
  3,
  'Netflix',
  NULL,
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Castle',
  'Crime',
  'Mystery writer helps police',
  '1',
  ARRAY['Crime', 'Drama', 'Mystery'],
  'English',
  '09/03',
  '05/16',
  3,
  'Torrent (Full Series)',
  NULL,
  'Torrent link for full series'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Lucifer',
  'Crime',
  'Devil helps police',
  '1',
  ARRAY['Crime', 'Drama', 'Fantasy'],
  'English',
  '01/16',
  '09/21',
  3,
  'Netflix',
  NULL,
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Sherlock',
  'Crime',
  'Sherlock Holmes',
  '1',
  ARRAY['Crime', 'Drama', 'Mystery'],
  'English',
  '10/07',
  '01/17',
  3,
  'BBC iPlayer',
  NULL,
  NULL
),
-- Fantasy Series
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Game of Thrones',
  'Fantasy',
  'Epic fantasy drama by George R.R. Martin',
  '1',
  ARRAY['Drama', 'Fantasy'],
  'English',
  '11/04',
  '05/19',
  3,
  'HBO',
  NULL,
  'Torrent link available online'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'The Witcher',
  'Fantasy',
  'Monster hunter Geralt in dark fantasy world',
  '3',
  ARRAY['Fantasy', 'Adventure'],
  'English',
  '12/19',
  NULL,
  3,
  'Netflix',
  'https://m.media-amazon.com/images/I/81nMygdz5YL._SL1500_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Stranger Things',
  'Fantasy',
  'Kids battle supernatural forces in 80s small town',
  '4',
  ARRAY['Drama', 'Fantasy'],
  'English',
  '07/16',
  NULL,
  3,
  'Netflix',
  'https://m.media-amazon.com/images/I/81LxV3Gb7UL._SL1500_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'House of Dragon',
  'Fantasy',
  'Prequel to Game of Thrones, houses vie for Iron Throne',
  '1',
  ARRAY['Fantasy', 'Drama'],
  'English',
  '08/22',
  NULL,
  3,
  'JioHotstar',
  'https://m.media-amazon.com/images/I/81nNuh7iD-L._SL1500_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'The Rings of Power',
  'Fantasy',
  'Middle-earth Second Age epic, fight for the Rings of Power',
  '2',
  ARRAY['Fantasy', 'Adventure'],
  'English',
  '09/22',
  NULL,
  3,
  'Prime Video',
  'https://m.media-amazon.com/images/I/91nqa8CojNL._SL1500_.jpg',
  NULL
),
-- Marvel Series
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'WandaVision',
  'Marvel',
  'Superhero sitcom',
  '1',
  ARRAY['Comedy', 'Fantasy'],
  'English',
  '01/21',
  '03/21',
  3,
  'Disney+ Hotstar',
  'https://m.media-amazon.com/images/I/713Ai9ULOcL._SL1500_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Loki',
  'Marvel',
  'Superhero fantasy',
  '1',
  ARRAY['Action', 'Adventure'],
  'English',
  '06/21',
  '07/21',
  3,
  'Disney+ Hotstar',
  'https://m.media-amazon.com/images/I/91Nq9pPZNmL._SL1500_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'The Falcon and the Winter Soldier',
  'Marvel',
  'Superhero action drama',
  '1',
  ARRAY['Action', 'Drama'],
  'English',
  '03/21',
  '05/21',
  3,
  'Hotstar',
  'https://m.media-amazon.com/images/I/81OWy1UbLtL._SL1500_.jpg',
  NULL
),
-- Other Popular Series
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Money Heist',
  'Other',
  'Heist crime drama',
  '5',
  ARRAY['Crime', 'Drama'],
  'Spanish',
  '05/17',
  '12/20',
  3,
  'Netflix',
  'https://m.media-amazon.com/images/I/81wGmMsqc4L._SL1500_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'The Big Bang Theory',
  'Sitcom',
  'Comedy about socially awkward scientists',
  '12',
  ARRAY['Comedy'],
  'English',
  '09/07',
  '05/19',
  3,
  'CBS',
  'https://m.media-amazon.com/images/I/71xRhGYEHyL._SL1500_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Friends',
  'Sitcom',
  'Friends navigating life in NYC',
  '10',
  ARRAY['Comedy'],
  'English',
  '09/94',
  '05/04',
  3,
  'Torrent',
  'https://m.media-amazon.com/images/I/71ktaHTGTUL._SL1500_.jpg',
  'Torrent link'
),
-- Tamil Series
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Suzhal',
  'Tamil',
  'Crime thriller series',
  '1',
  ARRAY['Crime', 'Thriller'],
  'Tamil',
  '03/23',
  NULL,
  3,
  'Prime Video',
  'https://m.media-amazon.com/images/I/8103vXwY9VL._SL1500_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Vadhandhi',
  'Tamil',
  'Crime thriller series',
  '1',
  ARRAY['Crime', 'Thriller'],
  'Tamil',
  '03/23',
  NULL,
  3,
  'Prime Video',
  'https://m.media-amazon.com/images/I/81-RpE3L+PL._SL1500_.jpg',
  NULL
); 