-- Bookworm Initial Data
-- Insert sample book records for vickyram.vira@gmail.com

-- Note: Replace 'USER_ID_PLACEHOLDER' with actual user UUID from auth.users table
-- WHERE email = 'vickyram.vira@gmail.com'

INSERT INTO bookworm (
  user_id,
  title,
  series,
  authors,
  genres,
  language,
  start_date,
  end_date,
  star_rating,
  read_download_link,
  pricing,
  cover_image_url,
  comment
) VALUES 
-- English Books
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Devil''s Paintbox',
  'The Witching Legacy',
  ARRAY['Robin Jarvis'],
  ARRAY['Fantasy', 'Dark fantasy'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://www.penguinrandomhouse.com/books/111991/the-devils-paintbox-by-victoria-mckernan/',
  'Paid',
  NULL, -- Cover via Open Library
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'The Exorcist',
  NULL,
  ARRAY['William Peter Blatty'],
  ARRAY['Horror', 'Occult'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://yourbookshelf.net/books/the-exorcist/',
  'Free',
  'https://upload.wikimedia.org/wikipedia/en/a/a9/TheExorcistNovel.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Spook''s Apprentice',
  'The Wardstone Chronicles',
  ARRAY['Joseph Delaney'],
  ARRAY['Dark fantasy', 'Children'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://in.pinterest.com/pin/free-download-the-spooks-apprentice-book-1-the-wardstone-chronicles--838091811891281014/',
  'Free',
  'https://upload.wikimedia.org/wikipedia/en/5/5f/Spook%27s_Apprentice_cover.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'The Slayers of Seth',
  NULL,
  ARRAY['Paul Doherty'],
  ARRAY['Mystery', 'Historical fiction'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://www.amazon.com/dp/0751502316',
  'Paid',
  NULL,
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Fire Chronicle',
  'Books of Beginning',
  ARRAY['John Stephens'],
  ARRAY['Fantasy', 'Adventure'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://www.amazon.com/Fire-Chronicle-Books-Beginning-Book-ebook/dp/B008A3ZPQ6',
  'Paid',
  NULL,
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'How to Train Your Dragon',
  'How to Train Your Dragon',
  ARRAY['Cressida Cowell'],
  ARRAY['Children', 'Fantasy', 'Adventure'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://cdn.bookey.app/files/pdf/book/en/how-to-train-your-dragon.pdf',
  'Free',
  'https://upload.wikimedia.org/wikipedia/en/c/c9/How_to_Train_Your_Dragon_%28Book_1%29.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Necropolis',
  'Alex Rider (spin-off)',
  ARRAY['Anthony Horowitz'],
  ARRAY['Spy', 'Young Adult'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://www.goodreads.com/book/show/2870651-necropolis',
  'Paid',
  'https://upload.wikimedia.org/wikipedia/en/4/4a/Necropolis_cover.jpeg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Origin',
  'Robert Langdon series',
  ARRAY['Dan Brown'],
  ARRAY['Thriller', 'Mystery'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://bookzoo.in/products/origin-ad20249',
  'Paid',
  'https://upload.wikimedia.org/wikipedia/en/a/a1/Origin_by_Dan_Brown.png',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Percy Jackson – The Titan''s Curse',
  'Percy Jackson & the Olympians (#3)',
  ARRAY['Rick Riordan'],
  ARRAY['Fantasy', 'Mythology', 'Young Adult'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://www.amazon.com/dp/0141382895',
  'Paid',
  'https://upload.wikimedia.org/wikipedia/en/4/44/Percy_Jackson_and_the_Titan%27s_Curse.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Harry Potter – Prisoner of Azkaban',
  'Harry Potter series (#3)',
  ARRAY['J.K. Rowling'],
  ARRAY['Fantasy', 'Young Adult'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://www.amazon.com/dp/0439136369',
  'Paid',
  'https://upload.wikimedia.org/wikipedia/en/5/5e/HP3_book_cover.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Harry Potter – Deathly Hallows',
  'Harry Potter series (#7)',
  ARRAY['J.K. Rowling'],
  ARRAY['Fantasy', 'Young Adult'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://www.amazon.com/dp/0545010225',
  'Paid',
  'https://upload.wikimedia.org/wikipedia/en/a/a9/Harry_Potter_and_the_Deathly_Hallows.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Harry Potter – Sorcerer''s Stone',
  'Harry Potter series (#1)',
  ARRAY['J.K. Rowling'],
  ARRAY['Fantasy', 'Young Adult'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://www.amazon.com/dp/0439708184',
  'Paid',
  'https://upload.wikimedia.org/wikipedia/en/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Revolution 2020',
  NULL,
  ARRAY['Chetan Bhagat'],
  ARRAY['Romance', 'Fiction', 'Contemporary'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://www.amazon.in/dp/8129135536',
  'Paid',
  'https://upload.wikimedia.org/wikipedia/en/d/d0/Revolution_2020_cover.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  '2 States',
  NULL,
  ARRAY['Chetan Bhagat'],
  ARRAY['Romance', 'Fiction', 'Contemporary'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://www.amazon.in/dp/8129115301',
  'Paid',
  'https://upload.wikimedia.org/wikipedia/en/c/c0/2_States_Book_Cover.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Half Girlfriend',
  NULL,
  ARRAY['Chetan Bhagat'],
  ARRAY['Romance', 'Fiction', 'Contemporary'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://www.amazon.in/dp/8129135722',
  'Paid',
  'https://upload.wikimedia.org/wikipedia/en/7/71/Half_Girlfriend.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Twilight',
  'Twilight saga',
  ARRAY['Stephenie Meyer'],
  ARRAY['Fantasy', 'Romance', 'Young Adult'],
  'English',
  '08/25',
  '08/25',
  3,
  'https://www.amazon.com/dp/0316015849',
  'Paid',
  'https://upload.wikimedia.org/wikipedia/en/9/9f/Twilight_cover.jpg',
  NULL
);

-- Tamil Books
INSERT INTO bookworm (
  user_id,
  title,
  series,
  authors,
  genres,
  language,
  start_date,
  end_date,
  star_rating,
  read_download_link,
  pricing,
  cover_image_url,
  comment
) VALUES 
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  '24 Roobai Theevu',
  NULL,
  ARRAY['Sujatha'],
  ARRAY['Fiction', 'Thriller', 'Short Stories'],
  'Tamil',
  '08/25',
  '08/25',
  3,
  'https://www.scribd.com/document/497671488/24-%E0%AE%B0%E0%AF%82%E0%AE%AA%E0%AE%BE%E0%AE%AF-%E0%AE%A4%E0%AF%80%E0%AE%B5%E0%AF%81-%E0%AE%9A%E0%AF%81%E0%AE%9C%E0%AE%BE%E0%AE%A4%E0%AE%BE',
  'Free',
  'https://m.media-amazon.com/images/I/51B5tdtYV6L.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  '5 Vazhi 3 Vaasal',
  NULL,
  ARRAY['Indira Soundarrajan'],
  ARRAY['Mystery', 'Supernatural', 'Thriller'],
  'Tamil',
  '08/25',
  '08/25',
  3,
  'https://tamilbookspdf.com/books/ainthu-vazhi-moondru-vaasal-by-indra-soundar-rajan/',
  'Free',
  'https://m.media-amazon.com/images/I/51t3r4A5b8L.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Alai Arasi',
  NULL,
  ARRAY['Sandilyan'],
  ARRAY['Historical Fiction', 'Romance'],
  'Tamil',
  '08/25',
  '08/25',
  3,
  'https://tamilbookspdf.com/books/alai-arasi-by-sandilyan/',
  'Free',
  'https://m.media-amazon.com/images/I/71ut6fZVJVL.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Ponniyin Selvan',
  NULL,
  ARRAY['Kalki'],
  ARRAY['Historical Fiction'],
  'Tamil',
  '08/25',
  '08/25',
  3,
  NULL,
  'Free',
  'https://m.media-amazon.com/images/I/41jcZrHvT8L.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'En Iniya Iyanthira',
  NULL,
  ARRAY['Sujatha'],
  ARRAY['Sci-Fi', 'Dystopian', 'Political Fiction'],
  'Tamil',
  '08/25',
  '08/25',
  3,
  'https://tamilbookspdf.com/books/en-iniya-iyandhira-by-sujatha-rangarajan/',
  'Free',
  'https://m.media-amazon.com/images/I/81Q+GQjLw6L.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Maaya',
  NULL,
  ARRAY['Sujatha'],
  ARRAY['Science Fiction', 'Thriller'],
  'Tamil',
  '08/25',
  '08/25',
  3,
  NULL,
  'Paid',
  'https://m.media-amazon.com/images/I/41iZQRD8zGL.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Kolai arangam',
  NULL,
  ARRAY['Sujatha'],
  ARRAY['Thriller', 'Mystery'],
  'Tamil',
  '08/25',
  '08/25',
  3,
  NULL,
  'Free',
  'https://m.media-amazon.com/images/I/41WnA6cN9oL.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Yavana Rani',
  NULL,
  ARRAY['Sandilyan'],
  ARRAY['Historical Fiction'],
  'Tamil',
  '08/25',
  '08/25',
  3,
  NULL,
  'Free',
  'https://m.media-amazon.com/images/I/41CXfCJwIJL.jpg',
  NULL
); 