-- Film Frenzy Initial Data
-- Insert sample movie records for vickyram.vira@gmail.com

INSERT INTO film_frenzy (
  user_id,
  title,
  verse,
  part,
  genres,
  language,
  date,
  imdb_rating,
  star_rating,
  watch_download_link,
  poster_image_url,
  comment
) VALUES 
-- Action/Adventure Movies
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Secret Society of Second Born Royals',
  NULL,
  NULL,
  ARRAY['Action', 'Adventure', 'Fantasy', 'Kids & Family'],
  'English',
  '12/20',
  5.0,
  3,
  'Disney+',
  'https://m.media-amazon.com/images/I/81bXjP474AL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Artemis Fowl',
  NULL,
  NULL,
  ARRAY['Science Fantasy', 'Adventure'],
  'English',
  '06/20',
  4.3,
  3,
  'Disney+',
  'https://m.media-amazon.com/images/I/81NzLelRRTL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Tomorrowland',
  NULL,
  NULL,
  ARRAY['Action', 'Adventure', 'Sci-Fi'],
  'English',
  '05/15',
  6.4,
  3,
  'Disney+',
  'https://m.media-amazon.com/images/I/71C09g2aybL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'The Sorcerer''s Apprentice',
  NULL,
  NULL,
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'English',
  '07/10',
  6.1,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/510RTVJUYWL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Immortals',
  NULL,
  NULL,
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'English',
  '11/11',
  6.0,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/51O2c+iC28L._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Jack the Giant Slayer',
  NULL,
  NULL,
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'English',
  '03/13',
  6.3,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/51QvK9AEnHL._AC_SY679_.jpg',
  NULL
),
-- Thriller/Drama Movies
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Catch Me If You Can',
  NULL,
  NULL,
  ARRAY['Biography', 'Crime', 'Drama'],
  'English',
  '02/12',
  8.1,
  3,
  'Netflix',
  'https://m.media-amazon.com/images/I/51rOnIjLqzL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'The Prestige',
  NULL,
  NULL,
  ARRAY['Drama', 'Mystery', 'Thriller'],
  'English',
  '06/10',
  8.5,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/51Q7r1gHBkL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'The Illusionist',
  NULL,
  NULL,
  ARRAY['Animation', 'Drama'],
  'English',
  '06/12',
  7.5,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/51lLqrSoX9L._AC_SY679_.jpg',
  NULL
),
-- Action/Sci-Fi Movies
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Mortal Kombat',
  NULL,
  '2021',
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'English',
  '04/21',
  6.1,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/71ssYXKNkYL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Assassin''s Creed',
  NULL,
  NULL,
  ARRAY['Action', 'Adventure', 'Sci-Fi'],
  'English',
  '12/16',
  5.6,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/81fAv89xKVL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Jumper',
  NULL,
  NULL,
  ARRAY['Action', 'Sci-Fi', 'Adventure'],
  'English',
  '08/02',
  6.1,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/718x8eRjZ3L._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Pacific Rim',
  NULL,
  '2013',
  ARRAY['Action', 'Adventure', 'Sci-Fi'],
  'English',
  '07/13',
  6.9,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/91MZl0alUuL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'I Am Legend',
  NULL,
  '2007',
  ARRAY['Action', 'Drama', 'Sci-Fi'],
  'English',
  '07/12',
  7.2,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/91p9xK2bJhL._AC_SY679_.jpg',
  NULL
),
-- Fantasy Movies
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Aladdin',
  NULL,
  '2019',
  ARRAY['Adventure', 'Family', 'Fantasy'],
  'English',
  '05/19',
  6.9,
  3,
  'Disney+',
  'https://m.media-amazon.com/images/I/81wZKbhO8yL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Prince of Persia',
  NULL,
  NULL,
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'English',
  '05/10',
  6.6,
  3,
  'Disney+',
  'https://m.media-amazon.com/images/I/91LMZ9sMMzL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Snow White and the Huntsman',
  NULL,
  NULL,
  ARRAY['Action', 'Adventure', 'Drama'],
  'English',
  '06/12',
  6.1,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/81RGrvJwVqL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Warcraft',
  NULL,
  NULL,
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'English',
  '06/16',
  6.7,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/91z9x0g6K5L._AC_SY679_.jpg',
  NULL
),
-- Mythology Movies
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Clash of the Titans',
  NULL,
  NULL,
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'English',
  '04/10',
  5.8,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/91W3sOXcM-L._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Wrath of the Titans',
  NULL,
  NULL,
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'English',
  '03/12',
  5.7,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/91FTVmW5XUL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Hercules',
  NULL,
  '2014',
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'English',
  '07/14',
  6.0,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/71IXeX8XkqL._AC_SY679_.jpg',
  NULL
),
-- Classic Movies
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Men in Black (MIB)',
  NULL,
  '1997',
  ARRAY['Action', 'Adventure', 'Comedy'],
  'English',
  '07/97',
  7.3,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/91TY-VEg5kL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Twilight',
  NULL,
  '2008',
  ARRAY['Drama', 'Fantasy', 'Romance'],
  'English',
  '08/11',
  5.3,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/91ZqYyqtMZL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'War of the Worlds',
  NULL,
  '2005',
  ARRAY['Adventure', 'Sci-Fi', 'Thriller'],
  'English',
  '05/06',
  6.5,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/81sov2rkCQL._AC_SY679_.jpg',
  NULL
),
-- Recent Movies
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Jungle Cruise',
  NULL,
  '2021',
  ARRAY['Action', 'Adventure', 'Comedy'],
  'English',
  '07/21',
  6.7,
  3,
  'Disney+',
  'https://m.media-amazon.com/images/I/91vL+UcHhkL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Uncharted',
  NULL,
  '2022',
  ARRAY['Action', 'Adventure'],
  'English',
  '02/22',
  6.3,
  3,
  'Amazon',
  'https://m.media-amazon.com/images/I/81YYmB1L6BL._AC_SY679_.jpg',
  NULL
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Bright',
  NULL,
  '2017',
  ARRAY['Action', 'Fantasy', 'Thriller'],
  'English',
  '12/17',
  6.3,
  3,
  'Netflix',
  'https://m.media-amazon.com/images/I/91-8VRAw+vL._AC_SY679_.jpg',
  NULL
); 