-- Otaku Hub Initial Data
-- Insert sample anime records for vickyram.vira@gmail.com

INSERT INTO otaku_hub (
  user_id,
  title,
  verse,
  season,
  genres,
  language,
  start_date,
  end_date,
  star_rating,
  watch_download_link,
  poster_image_url,
  comment
) VALUES 
-- Popular Shounen Anime
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'One Piece',
  'Anime',
  '1',
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/6/73245.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Naruto',
  'Anime',
  '1',
  ARRAY['Action', 'Adventure', 'Ninja'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Plex',
  'https://cdn.myanimelist.net/images/anime/13/17405.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Bleach',
  'Anime',
  '1',
  ARRAY['Action', 'Supernatural', 'Shounen'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/3/40451.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Dragon Ball Z',
  'Anime',
  '1',
  ARRAY['Action', 'Adventure', 'Martial Arts'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/5/32489.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'My Hero Academia',
  'Anime',
  '1',
  ARRAY['Action', 'Superhero'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Ani.ME',
  'https://cdn.myanimelist.net/images/anime/10/78745.jpg',
  'good'
),
-- Dark & Thriller Anime
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Death Note',
  'Anime',
  '1',
  ARRAY['Supernatural', 'Thriller', 'Mystery'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Netflix',
  'https://cdn.myanimelist.net/images/anime/9/9453.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Attack on Titan',
  'Anime',
  '1',
  ARRAY['Action', 'Dark Fantasy', 'Post-Apocalyptic'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/10/47347.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Demon Slayer',
  'Anime',
  '1',
  ARRAY['Action', 'Adventure', 'Supernatural'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/10/78745.jpg',
  'good'
),
-- Fantasy Adventure Anime
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Fairy Tail',
  'Anime',
  '1',
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/10/73274.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Seven Deadly Sins',
  'Anime',
  '1',
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Netflix',
  'https://cdn.myanimelist.net/images/anime/7/79469.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Black Clover',
  'Anime',
  '1',
  ARRAY['Action', 'Magic', 'Fantasy'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/9/9453.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Magi',
  'Anime',
  '1',
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/4/22045.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Fullmetal Alchemist',
  'Anime',
  '1',
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/1223/96541.jpg',
  'good'
),
-- Hunter & Special Powers
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Hunter x Hunter',
  'Anime',
  '1',
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'MX Player',
  'https://cdn.myanimelist.net/images/anime/11/33627.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Jujutsu Kaisen',
  'Anime',
  '1',
  ARRAY['Action', 'Supernatural', 'Fantasy'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/1171/103550.jpg',
  'ok'
),
-- Comedy & School Anime
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Assassination Classroom',
  'Anime',
  '1',
  ARRAY['Action', 'Comedy', 'School'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/8/76011.jpg',
  'ok'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'One Punch Man',
  'Anime',
  '1',
  ARRAY['Action', 'Comedy', 'Superhero'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/10/76014.jpg',
  'ok'
),
-- Sci-Fi & Modern Anime
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Dr. Stone',
  'Anime',
  '1',
  ARRAY['Action', 'Sci-Fi', 'Adventure'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/1502/100672.jpg',
  'ok'
),
-- Western Animation
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Dragon Prince',
  'Western',
  '4',
  ARRAY['Adventure', 'Fantasy'],
  'English',
  '08/25',
  '08/25',
  3,
  'Netflix',
  'https://cdn.myanimelist.net/images/anime/1/72066.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Arcane - League of Legends',
  'Western',
  '1',
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'English',
  '08/25',
  '08/25',
  3,
  'Netflix',
  'https://cdn.myanimelist.net/images/anime/17/94037.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Trollhunters - Tales of Arcadia',
  'Western',
  '3',
  ARRAY['Fantasy', 'Adventure'],
  'English',
  '08/25',
  '08/25',
  3,
  'Netflix',
  'https://cdn.myanimelist.net/images/anime/11/99985.jpg',
  'good'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Dragons: Race to the Edge',
  'Western',
  '6',
  ARRAY['Action', 'Adventure', 'Fantasy'],
  'English',
  '08/25',
  '08/25',
  3,
  'Netflix',
  'https://cdn.myanimelist.net/images/anime/9/76749.jpg',
  'good'
),
-- Recent Popular Anime
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Hell''s Paradise',
  'Anime',
  '1',
  ARRAY['Action', 'Supernatural'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/8/88331.jpg',
  'ok'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Tower of God',
  'Anime',
  '1',
  ARRAY['Action', 'Fantasy', 'Adventure'],
  'Korean',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/6/72699.jpg',
  'ok'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Record of Ragnarok',
  'Anime',
  '1',
  ARRAY['Action', 'Fantasy', 'Supernatural'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/14/92948.jpg',
  'ok'
),
-- Isekai & Fantasy
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'That Time I Got Reincarnated as a Slime',
  'Manhwa',
  '1',
  ARRAY['Fantasy', 'Isekai'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Hulu',
  'https://cdn.myanimelist.net/images/anime/11/94533.jpg',
  'ok'
),
(
  (SELECT id FROM auth.users WHERE email = 'vickyram.vira@gmail.com'),
  'Mushoku Tensei',
  'Anime',
  '1',
  ARRAY['Adventure', 'Fantasy', 'Isekai'],
  'Japanese',
  '08/25',
  '08/25',
  3,
  'Crunchyroll',
  'https://cdn.myanimelist.net/images/anime/8/88043.jpg',
  'ok'
); 